version: "3.8"
services:
  filebeat:
    image: docker.elastic.co/beats/filebeat:8.1.0
    container_name: "filebeat"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ./filebeat.docker.yml:/usr/share/filebeat/filebeat.yml:ro
    command: filebeat -e -strict.perms=false
    user: root
